# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nuno Alexandre
email: hi@nunoalexandre.com
description: Builder of software, product focused, designer wannabe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nunoalexandre.com" # the base hostname & protocol for your site
github_username: nunoalexandre
disqus_shortname: "nunoalexandre"
permalink: :year/:month/:day/:title
# Build settings
markdown: kramdown
fullname: Nuno Miguel Bento Alexandre
company_name: Nuno Alexandre
kvk_number: 76893081
vat_id: NL003127468B30
