# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nuno Alexandre
email: nunombalexandre at gmail
description: An aspiring software craftsman's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nunoalexandre.com" # the base hostname & protocol for your site
linkedin_username: nunombalexandre
github_username: nunoalexandre
twitter_username: nunombalexandre
disqus_shortname: "nunoalexandre"
permalink: :year/:month/:day/:title
# Build settings
markdown: kramdown
fullname: Nuno Miguel Bento Alexandre
